export const sensoLimitlessAbi = [
  {
    type: "function",
    name: "register",
    inputs: [{ name: "sponsor", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "purchaseClub",
    inputs: [{ name: "level", type: "uint8" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "purchasePilot",
    inputs: [{ name: "level", type: "uint8" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "processPending",
    inputs: [{ name: "maxSteps", type: "uint256" }],
    outputs: [{ name: "processed", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "withdrawRef", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pendingLength",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDaiBalance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSltBalance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rootSponsor",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activated",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "users",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "sponsor", type: "address" },
      { name: "registered", type: "bool" },
      { name: "registeredAt", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "directReferrals",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "countQualifiedDirectReferrals",
    inputs: [
      { name: "user", type: "address" },
      { name: "matrixType", type: "uint8" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "clubPackages",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint8" },
    ],
    outputs: [
      { name: "owned", type: "bool" },
      { name: "isManual", type: "bool" },
      { name: "cyclesCompleted", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pilotPackages",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint8" },
    ],
    outputs: [
      { name: "owned", type: "bool" },
      { name: "isManual", type: "bool" },
      { name: "cyclesCompleted", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activeClubMatrix",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint8" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activePilotMatrix",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint8" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "clubMatrices",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "level", type: "uint8" },
      { name: "slotsFilled", type: "uint8" },
      { name: "active", type: "bool" },
      { name: "cycleCompleted", type: "bool" },
      { name: "isRebirth", type: "bool" },
      { name: "parentMatrixId", type: "uint256" },
      { name: "cycleNumber", type: "uint32" },
      { name: "createdAt", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pilotMatrices",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "level", type: "uint8" },
      { name: "slotsFilled", type: "uint8" },
      { name: "active", type: "bool" },
      { name: "cycleCompleted", type: "bool" },
      { name: "isRebirth", type: "bool" },
      { name: "parentMatrixId", type: "uint256" },
      { name: "cycleNumber", type: "uint32" },
      { name: "createdAt", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "clubSlotUsers",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address[4]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pilotSlotUsers",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address[2]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "clubAmounts",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pilotAmounts",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "clubMatrixCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pilotMatrixCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "UserRegistered",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "sponsor", type: "address", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClubPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: true },
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "isRebirth", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PilotPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: true },
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "isManual", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClubPlacement",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "slotIndex", type: "uint8", indexed: false },
      { name: "sponsor", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "isSpillover", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PilotPlacement",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "slotIndex", type: "uint8", indexed: false },
      { name: "sponsor", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "isSpillover", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClubCycleCompleted",
    inputs: [
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "withdrawAmount", type: "uint256", indexed: false },
      { name: "reinvestAmount", type: "uint256", indexed: false },
      { name: "cyclesCompleted", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PilotCycleCompleted",
    inputs: [
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "poolAmount", type: "uint256", indexed: false },
      { name: "cyclesCompleted", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClubRebirthCreated",
    inputs: [
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "parentMatrixId", type: "uint256", indexed: false },
      { name: "cycleNumber", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PilotRebirthCreated",
    inputs: [
      { name: "matrixId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "parentMatrixId", type: "uint256", indexed: false },
      { name: "cycleNumber", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AutoUpgrade",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "matrixType", type: "uint8", indexed: false },
      { name: "fromLevel", type: "uint8", indexed: false },
      { name: "toLevel", type: "uint8", indexed: false },
      { name: "idempotencyKey", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "IncomePaid",
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "incomeType", type: "uint8", indexed: false },
      { name: "matrixType", type: "uint8", indexed: false },
      { name: "level", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TokenReward",
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "source", type: "address", indexed: true },
      { name: "rewardType", type: "uint8", indexed: false },
      { name: "matrixType", type: "uint8", indexed: false },
      { name: "level", type: "uint8", indexed: false },
      { name: "laeAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Withdraw",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "withdrawRef", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PendingProcessed",
    inputs: [
      { name: "kind", type: "uint8", indexed: false },
      { name: "user", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
] as const;

export const CLUB_LEVELS = 12;
export const PILOT_LEVELS = 8;
export const CLUB_SLOTS = 4;
export const PILOT_SLOTS = 2;
