-- PDF compliance: new IncomeType values
ALTER TYPE "IncomeType" ADD VALUE IF NOT EXISTS 'PILOT_INCENTIVE';
ALTER TYPE "IncomeType" ADD VALUE IF NOT EXISTS 'SPONSOR_PAYMENT';
ALTER TYPE "IncomeType" ADD VALUE IF NOT EXISTS 'FIRST_LINE_BONUS';
