/** BTitanXMatrix / LAE Club Matrix — deployed BSC Testnet ABI (live contract) */

export const laeClubMatrixAbi = [
  {
    type: "function",
    name: "registrationExt",
    inputs: [{ name: "referrerId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isUserExists",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addressToId",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "idToAddress",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastUserId",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalProjectInvestment",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "levelTokenCost",
    inputs: [{ name: "", type: "uint8" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LAST_LEVEL",
    inputs: [],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MATRIX_SIZE",
    inputs: [],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PAYMENT_TOKEN",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserDetails",
    inputs: [{ name: "userId", type: "uint256" }],
    outputs: [
      { name: "userAddress", type: "address" },
      { name: "referrerAddress", type: "address" },
      { name: "referrerId", type: "uint256" },
      { name: "partnersCount", type: "uint256" },
      { name: "activeSlotsCount", type: "uint8" },
      { name: "teamSize", type: "uint256" },
      { name: "registrationTimestamp", type: "uint256" },
      { name: "totalIncome", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDirectPartnerAddresses",
    inputs: [{ name: "userId", type: "uint256" }],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDirectPartnerIds",
    inputs: [{ name: "userId", type: "uint256" }],
    outputs: [{ type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUserSlotActive",
    inputs: [{ name: "userId", type: "uint256" }, { name: "slot", type: "uint8" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usersXMatrix",
    inputs: [{ name: "userAddress", type: "address" }, { name: "level", type: "uint8" }],
    outputs: [
      { name: "currentReferrer", type: "address" },
      { name: "reinvestCount", type: "uint256" },
      { name: "heldTokenForUpgrade", type: "uint256" },
      { name: "lastSpillUnderReceiverIndex", type: "uint256" },
      { name: "totalTeamSize", type: "uint256" },
      { name: "totalEarning", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usersXMatrixReferrals",
    inputs: [{ name: "userAddress", type: "address" }, { name: "level", type: "uint8" }],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CLUB_POOL_ADDRESS",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TREASURY_POOL_ADDRESS",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimLaeRewards",
    inputs: [],
    outputs: [{ name: "claimedAmount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getLaeRewardSummary",
    inputs: [{ name: "userAddress", type: "address" }],
    outputs: [
      { name: "allocated", type: "uint256" },
      { name: "released", type: "uint256" },
      { name: "claimable", type: "uint256" },
      { name: "claimed", type: "uint256" },
      { name: "locked", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGlobalLaeStats",
    inputs: [],
    outputs: [
      { name: "allocated", type: "uint256" },
      { name: "claimed", type: "uint256" },
      { name: "liquidityCollected", type: "uint256" },
      { name: "pendingLocked", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "matrixDistributionBps",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDirectPartnerCount",
    inputs: [{ name: "userAddress", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "directRequirementByMonth",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "monthlyReleaseBps",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Registration",
    inputs: [
      { name: "userId", type: "uint256", indexed: true },
      { name: "referrerId", type: "uint256", indexed: true },
      { name: "userAddress", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "TokenReceived",
    inputs: [
      { name: "receiverId", type: "uint256", indexed: true },
      { name: "fromId", type: "uint256", indexed: true },
      { name: "from", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClubPoolPayment",
    inputs: [
      { name: "refId", type: "uint256", indexed: true },
      { name: "userId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "NewUserPlace",
    inputs: [
      { name: "user", type: "uint256", indexed: true },
      { name: "referrer", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "cycle", type: "uint256", indexed: false },
      { name: "spot", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Spillover",
    inputs: [
      { name: "referrerId", type: "uint256", indexed: true },
      { name: "receiverId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "cycle", type: "uint256", indexed: false },
      { name: "virtualSpot", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Reinvest",
    inputs: [
      { name: "userId", type: "uint256", indexed: true },
      { name: "newReferrerId", type: "uint256", indexed: true },
      { name: "callerId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Upgrade",
    inputs: [
      { name: "userId", type: "uint256", indexed: true },
      { name: "newReferrerId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MissedIncome",
    inputs: [
      { name: "receiverId", type: "uint256", indexed: true },
      { name: "userId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LaeRewardAllocated",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "scheduleIndex", type: "uint256", indexed: true },
      { name: "laeAmount", type: "uint256", indexed: false },
      { name: "liquidityContribution", type: "uint256", indexed: false },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LaeRewardClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PoolAddressesUpdated",
    inputs: [
      { name: "newClubPool", type: "address", indexed: true },
      { name: "newTreasuryPool", type: "address", indexed: true },
    ],
  },
] as const;

export const laeCoinAbi = [
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalBurned", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "maxSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "circulatingSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allowance", inputs: [{ name: "", type: "address" }, { name: "", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "p2pEnabled", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "p2pPaymentToken", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "nextOrderId", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "p2pOrders",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "seller", type: "address" },
      { name: "laeAmount", type: "uint256" },
      { name: "pricePerLae", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createP2POrder",
    inputs: [{ name: "laeAmount", type: "uint256" }, { name: "pricePerLae", type: "uint256" }],
    outputs: [{ name: "orderId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "fillP2POrder", inputs: [{ name: "orderId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "cancelP2POrder", inputs: [{ name: "orderId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "treasuryWallet", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "liquidityWallet", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "matrixContract", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "rewardPoolRemaining", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "transfer", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "burn", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const laeStakingAbi = [
  { type: "function", name: "totalStaked", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "rewardRateBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "pendingReward", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "stakes",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "amount", type: "uint256" },
      { name: "stakedAt", type: "uint256" },
      { name: "lastClaim", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "stake", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claim", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unstake", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const erc20BalanceAbi = [
  { type: "function", name: "balanceOf", inputs: [{ name: "", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
] as const;
