/** LAEClubMatrix — 15-slot × 14-position matrix contract ABI (frontend) */
export const laeClubMatrixAbi = [
  {
    type: "function",
    name: "registrationExt",
    inputs: [{ name: "referrerId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addressToId",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "idToAddress",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastUserId",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "levelTokenCost",
    inputs: [{ name: "level", type: "uint8" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PAYMENT_TOKEN",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TREASURY_POOL_ADDRESS",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CLUB_POOL_ADDRESS",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserDetails",
    inputs: [{ name: "userId", type: "uint256" }],
    outputs: [
      { name: "userAddress", type: "address" },
      { name: "referrerAddress", type: "address" },
      { name: "referrerId", type: "uint256" },
      { name: "partnersCount", type: "uint256" },
      { name: "activeSlotsCount", type: "uint8" },
      { name: "teamSize", type: "uint256" },
      { name: "registrationTimestamp", type: "uint256" },
      { name: "totalIncome", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDirectPartnerIds",
    inputs: [{ name: "userId", type: "uint256" }],
    outputs: [{ type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUserSlotActive",
    inputs: [
      { name: "userId", type: "uint256" },
      { name: "slot", type: "uint8" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usersXMatrix",
    inputs: [
      { name: "userAddress", type: "address" },
      { name: "level", type: "uint8" },
    ],
    outputs: [
      { name: "currentReferrer", type: "address" },
      { name: "reinvestCount", type: "uint256" },
      { name: "heldTokenForUpgrade", type: "uint256" },
      { name: "lastSpillUnderReceiverIndex", type: "uint256" },
      { name: "totalTeamSize", type: "uint256" },
      { name: "totalEarning", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usersXMatrixReferrals",
    inputs: [
      { name: "userAddress", type: "address" },
      { name: "level", type: "uint8" },
    ],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUserExists",
    inputs: [{ name: "userAddress", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLaeRewardSummary",
    inputs: [{ name: "userAddress", type: "address" }],
    outputs: [
      { name: "allocated", type: "uint256" },
      { name: "released", type: "uint256" },
      { name: "claimable", type: "uint256" },
      { name: "claimed", type: "uint256" },
      { name: "locked", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimLaeRewards",
    inputs: [],
    outputs: [{ name: "claimedAmount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Registration",
    inputs: [
      { name: "userId", type: "uint256", indexed: true },
      { name: "referrerId", type: "uint256", indexed: true },
      { name: "userAddress", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "NewUserPlace",
    inputs: [
      { name: "user", type: "uint256", indexed: true },
      { name: "referrer", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "cycle", type: "uint256", indexed: false },
      { name: "spot", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TokenReceived",
    inputs: [
      { name: "receiverId", type: "uint256", indexed: true },
      { name: "fromId", type: "uint256", indexed: true },
      { name: "from", type: "address", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClubPoolPayment",
    inputs: [
      { name: "refId", type: "uint256", indexed: true },
      { name: "userId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Reinvest",
    inputs: [
      { name: "userId", type: "uint256", indexed: true },
      { name: "newReferrerId", type: "uint256", indexed: true },
      { name: "callerId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Upgrade",
    inputs: [
      { name: "userId", type: "uint256", indexed: true },
      { name: "newReferrerId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MissedIncome",
    inputs: [
      { name: "receiverId", type: "uint256", indexed: true },
      { name: "userId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LapseIncome",
    inputs: [
      { name: "receiverId", type: "uint256", indexed: true },
      { name: "fromId", type: "uint256", indexed: true },
      { name: "level", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LaeRewardAllocated",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "scheduleIndex", type: "uint256", indexed: true },
      { name: "laeAmount", type: "uint256", indexed: false },
      { name: "liquidityContribution", type: "uint256", indexed: false },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LaeRewardClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

/** @deprecated — use laeClubMatrixAbi */
export const matrixCoreAbi = laeClubMatrixAbi;
