/**
 * B-TITAN plan data + mock user state, derived directly from the
 * "Updated B Titan Presentation" deck. Powers every dashboard page.
 *
 * Plan facts:
 *  - Entry 0.001 BTC, 12-slot power system (doubling).
 *  - Slot income = 7x price (slot 12 = 9x).
 *  - Unlimited recycling → 61.342 BTC total matrix potential.
 *  - Royal Pool from every 4th position after cycle 1.
 *  - Welcome Pass NFT: 0.001 → 1 BTC target, 100-day lock.
 *  - Ranks: Rising/Prime/Royal/Legendary at slots 3/6/9/12, 25% reward each.
 */

export const BTC_USD = 104250;

export function btcToUsd(btc: number): string {
  return (btc * BTC_USD).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

export function fmtBtc(btc: number, dp = 3): string {
  return `${btc.toFixed(dp)} BTC`;
}

export type Slot = {
  id: number;
  price: number; // BTC
  income: number; // BTC per completed slot
  multiplier: number; // recycle multiplier after 12th recycle
  totalIncome: number; // BTC potential
  active: boolean;
  cycles: number; // completed recycles
  members: number; // members filled in current cycle (of 14)
};

// price → income → recycle multiplier → total potential (from slides 5/10/12)
const SLOT_TABLE: [number, number, number, number][] = [
  [0.001, 0.007, 12, 0.084],
  [0.002, 0.014, 11, 0.154],
  [0.004, 0.028, 10, 0.28],
  [0.008, 0.056, 9, 0.504],
  [0.016, 0.112, 8, 0.896],
  [0.032, 0.224, 7, 1.568],
  [0.064, 0.448, 6, 2.688],
  [0.128, 0.896, 5, 4.48],
  [0.256, 1.792, 4, 7.168],
  [0.512, 3.584, 3, 10.752],
  [1.024, 7.168, 2, 14.336],
  [2.048, 18.432, 1, 18.432],
];

// Mock: user currently active up to slot 5, with some recycles/fill.
const ACTIVE_UPTO = 5;
const CYCLES = [9, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0];
const MEMBERS = [14, 14, 11, 6, 3, 0, 0, 0, 0, 0, 0, 0];

export const slots: Slot[] = SLOT_TABLE.map(([price, income, multiplier, totalIncome], i) => ({
  id: i + 1,
  price,
  income,
  multiplier,
  totalIncome,
  active: i + 1 <= ACTIVE_UPTO,
  cycles: CYCLES[i],
  members: MEMBERS[i],
}));

export const TOTAL_MATRIX_POTENTIAL = 61.342;

// ---- Ranks (slide 16/17) -------------------------------------------------
export type Rank = {
  id: number;
  name: string;
  card: string;
  targetSlot: number;
  reward: number; // %
  requirement: string;
  achieved: boolean;
};

export const ranks: Rank[] = [
  { id: 1, name: "Rising", card: "Orichalcum Plate", targetSlot: 3, reward: 25, requirement: "Refer 5 directly", achieved: true },
  { id: 2, name: "Prime", card: "Draconium Shard", targetSlot: 6, reward: 25, requirement: "Upgrade 5 directs to Slot 5", achieved: false },
  { id: 3, name: "Royal", card: "Modular Shard", targetSlot: 9, reward: 25, requirement: "Team reaches Slot 9 depth", achieved: false },
  { id: 4, name: "Legendary", card: "Adamantine Crown", targetSlot: 12, reward: 25, requirement: "Complete the full 12-slot engine", achieved: false },
];

// ---- Income breakdown (slide 7/8/9) -------------------------------------
export type IncomeType = {
  key: string;
  label: string;
  earned: number; // BTC
  desc: string;
};

export const incomeTypes: IncomeType[] = [
  { key: "level", label: "Level Income", earned: 0.0421, desc: "From your 1st & 2nd downlines across active slots" },
  { key: "upline", label: "Upline Income", earned: 0.0288, desc: "Spillover income generated by your 1st & 2nd uplines" },
  { key: "recycle", label: "Recycle Income", earned: 0.0186, desc: "Free slot recycles paying out on every cycle" },
  { key: "spillover", label: "Auto-Spillover", earned: 0.0152, desc: "Auto-placed members from both uplines and downlines" },
  { key: "royal", label: "Royal Pool", earned: 0.0094, desc: "Every 4th position after cycle 1 — passive pool income" },
  { key: "rank", label: "Rank Reward", earned: 0.0063, desc: "25% rank rewards on rank achievement" },
];

export const totalEarned = incomeTypes.reduce((a, b) => a + b.earned, 0);

// ---- Team / network ------------------------------------------------------
export type Member = {
  id: string;
  username: string;
  joined: string;
  slot: number;
  team: number;
  earned: number;
  status: "active" | "idle";
  leg: "L1" | "L2" | "Direct";
};

export const directReferrals: Member[] = [
  { id: "BT-10241", username: "satoshi_x", joined: "2026-05-02", slot: 6, team: 142, earned: 0.214, status: "active", leg: "Direct" },
  { id: "BT-10242", username: "cryptoraja", joined: "2026-05-08", slot: 4, team: 63, earned: 0.092, status: "active", leg: "Direct" },
  { id: "BT-10243", username: "node_master", joined: "2026-05-15", slot: 5, team: 88, earned: 0.131, status: "active", leg: "Direct" },
  { id: "BT-10244", username: "btc_amir", joined: "2026-05-21", slot: 3, team: 27, earned: 0.041, status: "active", leg: "Direct" },
  { id: "BT-10245", username: "hodl_queen", joined: "2026-05-29", slot: 2, team: 9, earned: 0.014, status: "idle", leg: "Direct" },
  { id: "BT-10246", username: "titan_neo", joined: "2026-06-03", slot: 1, team: 2, earned: 0.006, status: "active", leg: "Direct" },
];

export const teamMembers: Member[] = [
  ...directReferrals,
  { id: "BT-10311", username: "lae_wolf", joined: "2026-05-10", slot: 3, team: 31, earned: 0.046, status: "active", leg: "L1" },
  { id: "BT-10312", username: "minerpro", joined: "2026-05-12", slot: 2, team: 12, earned: 0.018, status: "active", leg: "L1" },
  { id: "BT-10313", username: "ada_blue", joined: "2026-05-18", slot: 4, team: 40, earned: 0.061, status: "active", leg: "L1" },
  { id: "BT-10401", username: "zen_chain", joined: "2026-05-22", slot: 1, team: 3, earned: 0.007, status: "active", leg: "L2" },
  { id: "BT-10402", username: "spark_io", joined: "2026-05-26", slot: 2, team: 6, earned: 0.014, status: "idle", leg: "L2" },
  { id: "BT-10403", username: "vault_77", joined: "2026-06-01", slot: 1, team: 1, earned: 0.006, status: "active", leg: "L2" },
];

export const teamStats = {
  total: 318,
  directs: directReferrals.length,
  active: 281,
  idle: 37,
  todayJoins: 12,
};

// ---- Transactions --------------------------------------------------------
export type Tx = {
  id: string;
  type: "income" | "slot" | "withdraw" | "deposit" | "royal" | "rank" | "recycle";
  label: string;
  amount: number; // BTC, +/-
  date: string;
  status: "completed" | "pending";
  hash: string;
};

export const transactions: Tx[] = [
  { id: "TX-90412", type: "income", label: "Level income · Slot 5", amount: 0.0112, date: "2026-06-08 09:14", status: "completed", hash: "0x7af3…21bd" },
  { id: "TX-90411", type: "recycle", label: "Slot 4 recycle payout", amount: 0.056, date: "2026-06-08 07:41", status: "completed", hash: "0x19c2…88ea" },
  { id: "TX-90410", type: "royal", label: "Royal Pool distribution", amount: 0.0041, date: "2026-06-07 23:02", status: "completed", hash: "0x55de…0f3a" },
  { id: "TX-90409", type: "withdraw", label: "Withdrawal to wallet", amount: -0.05, date: "2026-06-07 18:30", status: "completed", hash: "0x9b1f…77c4" },
  { id: "TX-90408", type: "slot", label: "Slot 5 activation", amount: -0.016, date: "2026-06-07 12:10", status: "completed", hash: "0x2d44…ab90" },
  { id: "TX-90407", type: "income", label: "Upline spillover income", amount: 0.0072, date: "2026-06-06 20:55", status: "completed", hash: "0xc3a7…1142" },
  { id: "TX-90406", type: "rank", label: "Rank reward · Rising", amount: 0.0063, date: "2026-06-06 14:21", status: "completed", hash: "0x88fb…9920" },
  { id: "TX-90405", type: "deposit", label: "BTC deposit", amount: 0.12, date: "2026-06-05 10:03", status: "completed", hash: "0x4e90…33dc" },
  { id: "TX-90404", type: "income", label: "Level income · Slot 3", amount: 0.0028, date: "2026-06-05 08:47", status: "completed", hash: "0xa1b2…c3d4" },
  { id: "TX-90403", type: "withdraw", label: "Withdrawal to wallet", amount: -0.03, date: "2026-06-04 16:12", status: "pending", hash: "0xf00d…beef" },
];

// ---- Wallet --------------------------------------------------------------
export const wallet = {
  available: 0.1284,
  locked: 0.016, // in active slots
  totalEarned: totalEarned,
  totalWithdrawn: 0.08,
  btcAddress: "bc1qtitan7x9f3a8k2m4n6p0q2r4s6t8u0v2w4x6y8z",
};

// ---- NFT (Welcome Pass) --------------------------------------------------
export const nft = {
  name: "Welcome Pass #01",
  startPrice: 0.001,
  currentPrice: 0.0186,
  targetPrice: 1,
  lockDays: 100,
  daysHeld: 71,
  minted: "2026-03-29",
};

// ---- Royal Pool ----------------------------------------------------------
export const royalPool = {
  totalPool: 8.42,
  nftLiquidityShare: 0.5,
  myEarned: 0.0094,
  myPositions: 7,
  nextDistribution: "14h 22m",
};

// ---- Leaderboard ---------------------------------------------------------
export type LeaderRow = { rank: number; username: string; slot: number; team: number; earned: number; tier: string };
export const leaderboard: LeaderRow[] = [
  { rank: 1, username: "titan_king", slot: 12, team: 14820, earned: 58.21, tier: "Legendary" },
  { rank: 2, username: "btc_whale", slot: 12, team: 11240, earned: 49.07, tier: "Legendary" },
  { rank: 3, username: "satoshi_x", slot: 11, team: 9810, earned: 41.66, tier: "Royal" },
  { rank: 4, username: "node_master", slot: 10, team: 7430, earned: 33.12, tier: "Royal" },
  { rank: 5, username: "cryptoraja", slot: 10, team: 6190, earned: 28.94, tier: "Royal" },
  { rank: 6, username: "ada_blue", slot: 9, team: 5120, earned: 22.41, tier: "Royal" },
  { rank: 7, username: "minerpro", slot: 8, team: 3980, earned: 16.88, tier: "Prime" },
  { rank: 8, username: "you", slot: 5, team: 318, earned: totalEarned, tier: "Rising" },
];

// ---- Current user --------------------------------------------------------
export const user = {
  username: "you",
  id: "BT-10240",
  joined: "2026-03-29",
  rank: "Rising",
  highestSlot: ACTIVE_UPTO,
  referralCode: "BTITAN-10240",
  referralLink: "https://btitan.net/join?ref=BTITAN-10240",
  avatarSeed: "you",
};

// ---- Announcements -------------------------------------------------------
export const announcements = [
  { id: 1, title: "Slot 12 global recycle milestone reached", body: "The network just crossed 14,800 completed Slot-12 recycles. Royal Pool liquidity is at an all-time high.", date: "2026-06-08", tag: "Milestone" },
  { id: 2, title: "NFT Liquidity Pool price update", body: "Welcome Pass NFT floor moved to 0.0186 BTC as 50% of Royal Pool positions flowed into liquidity.", date: "2026-06-06", tag: "NFT" },
  { id: 3, title: "Instant withdrawals — now sub-second", body: "Smart-contract settlement optimised; withdrawals now confirm in under a second on-chain.", date: "2026-06-02", tag: "Network" },
  { id: 4, title: "Rank reward distribution complete", body: "This month's Rising / Prime / Royal / Legendary rank rewards (25% each) have been distributed.", date: "2026-05-30", tag: "Rewards" },
];

// ---- Earnings sparkline (last 14 days, BTC) ------------------------------
export const earningsSeries = [
  0.002, 0.003, 0.0025, 0.004, 0.0052, 0.0048, 0.006, 0.0071, 0.0065,
  0.008, 0.0092, 0.0088, 0.0104, 0.0121,
];
