// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {MatrixStorage} from "./MatrixStorage.sol";

/**
 * @title MatrixIncome
 * @notice Implements the exact 14-position income distribution, the slot-2
 *         opening trigger, and the lapse routing to ownerId.
 *
 * @dev Position rules (matrix owner = M, entry amount = X):
 *
 *   p1  -> M's 1st upline (sponsor)              | 90/10, lapse->ownerId
 *   p2  -> M's 2nd upline (sponsor's sponsor)    | 90/10, lapse->ownerId
 *   p3  -> M                                     | 90/10
 *   p4  -> Treasury (funds slot 2)               | 100% treasury
 *   p5  -> cycle 1: Treasury (funds slot 2)      | 100% treasury
 *          cycle >=2: M                          | 90/10
 *   p6  -> M                                     | 90/10
 *   p7  -> M.position[1] (1st downline) else M   | 90/10
 *   p8  -> M                                     | 90/10
 *   p9  -> M                                     | 90/10
 *   p10 -> M.position[2] (2nd downline) else M   | 90/10
 *   p11 -> M                                     | 90/10
 *   p12 -> M                                     | 90/10
 *   p13 -> 1st DL's 1st DL (pos 3) → 2nd DL's 1st DL (pos 5) → continue → You
 *   p14 -> Treasury (recycle trigger)            | 100% treasury
 *
 * When p4 AND p5 are filled in cycle 1, slot 2 opens automatically.
 */
abstract contract MatrixIncome is MatrixStorage {
    using SafeERC20 for IERC20;

    /// @dev Routes the income generated by filling `position` in M's matrix.
    function _distributeIncome(uint32 matrixOwnerId, uint32 cycleId, uint8 position, uint32 fromUserId)
        internal
    {
        uint256 X = entryPrice;

        // Treasury-only positions: 100% to treasury, no split, no lapse.
        if (position == 4 || (position == 5 && cycleId == 1) || position == 14) {
            _toTreasury(matrixOwnerId, fromUserId, position, X);
            if (position == 5 && cycleId == 1) {
                _openNextSlot(matrixOwnerId); // slot 2 opens once p4+p5 are funded
            }
            return;
        }

        uint32 receiver = _resolveReceiver(matrixOwnerId, cycleId, position);
        _payout(fromUserId, matrixOwnerId, receiver, position, X);
    }

    /// @dev Resolves the intended user receiver for a 90/10 position.
    function _resolveReceiver(uint32 M, uint32 cycleId, uint8 position) internal view returns (uint32) {
        if (position == 1) return _uplineOf(M, 1);
        if (position == 2) return _uplineOf(M, 2);
        if (position == 7) {
            uint32 d1 = users[M].cycles[cycleId].positions[1];
            return _isReceivable(d1) ? d1 : M;
        }
        if (position == 10) {
            uint32 d2 = users[M].cycles[cycleId].positions[2];
            return _isReceivable(d2) ? d2 : M;
        }
        if (position == 13) {
            return _resolvePosition13(M, cycleId);
        }
        // p3, p5(cycle>=2), p6, p8, p9, p11, p12 -> the matrix owner.
        return M;
    }

    /**
     * @dev Position 13 receiver: search within M's current matrix tree.
     *
     *      Business plan (matches the diagram):
     *        1. First Direct Downline's First Downline  → pos-3 occupant (left child of p1)
     *        2. Second Direct Downline's First Downline → pos-5 occupant (left child of p2)
     *        3. Continue search: p4, p6, p7 … p12 (remaining filled positions)
     *        4. Fallback to M (You)
     *
     *      Positions 1–12 are always filled before p13 is reached.
     */
    function _resolvePosition13(uint32 M, uint32 cycleId) internal view returns (uint32) {
        uint32[15] storage pos = users[M].cycles[cycleId].positions;
        uint8[10] memory order = [3, 5, 4, 6, 7, 8, 9, 10, 11, 12];
        for (uint256 i = 0; i < order.length; i++) {
            uint32 candidate = pos[order[i]];
            if (_isReceivable(candidate)) return candidate;
        }
        return M;
    }

    /// @dev 90/10 payout. 10% to treasury (liquidity); 90% to receiver or lapse.
    function _payout(uint32 fromUserId, uint32 M, uint32 receiver, uint8 position, uint256 X) internal {
        uint256 treasuryCut = (X * TREASURY_BPS) / BPS; // 10%
        uint256 userCut = X - treasuryCut; // 90%

        // Liquidity / treasury leg (always paid).
        _send(treasuryWallet, treasuryCut);
        totalTreasuryIncome += treasuryCut;
        emit TreasuryIncome(M, position, treasuryCut);

        if (_isReceivable(receiver)) {
            _send(users[receiver].wallet, userCut);
            users[receiver].totalEarned += uint128(userCut);
            totalUserIncome += userCut;
            incomeHistory[receiver].push(
                IncomeRecord(fromUserId, M, position, 0, uint128(userCut))
            );
            emit IncomeDistributed(fromUserId, receiver, position, userCut);
        } else {
            // Lapsed: receiver missing / blocked / unqualified -> ownerId.
            address ownerWallet = users[ownerId].wallet;
            _send(ownerWallet, userCut);
            totalLapsedIncome += userCut;
            users[ownerId].totalEarned += uint128(userCut);
            incomeHistory[ownerId].push(
                IncomeRecord(fromUserId, M, position, 2, uint128(userCut))
            );
            emit LapsedIncome(receiver, position, userCut);
        }
    }

    /// @dev 100% to treasury (slot funding / recycle).
    function _toTreasury(uint32 M, uint32 fromUserId, uint8 position, uint256 X) internal {
        _send(treasuryWallet, X);
        totalTreasuryIncome += X;
        incomeHistory[ownerId].push(IncomeRecord(fromUserId, M, position, 1, uint128(X)));
        emit TreasuryIncome(M, position, X);
    }

    /// @dev Opens the next slot for a user (extensible progression).
    function _openNextSlot(uint32 userId) internal {
        User storage u = users[userId];
        uint32 next = u.highestSlot + 1;
        if (u.slotActive[next]) return;
        u.slotActive[next] = true;
        u.highestSlot = next;
        if (next == 2) {
            u.cycles[1].slot2Opened = true;
        }
        emit SlotOpened(userId, next);
    }

    /// @dev SafeERC20 transfer wrapper (skips zero-value/zero-address noops).
    function _send(address to, uint256 amount) internal {
        if (amount == 0 || to == address(0)) return;
        IERC20(paymentToken).safeTransfer(to, amount);
    }
}
